<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FraudWatch.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="6.0.16" />
    <PackageReference Include="StackExchange.Redis" Version="2.6.122" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.3" />
    <PackageReference Include="System.Text.Json" Version="6.0.9" />
    <PackageReference Include="Npgsql" Version="6.0.11" />
    <PackageReference Include="Dapper" Version="2.0.123" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FraudWatch.Core\FraudWatch.Core.csproj" />
  </ItemGroup>

</Project>
